name: 🚀 Create Production Builds

on:
  push:
    branches:
      - build/production

jobs:
  build_android:
    type: build
    params:
      platform: android

  # build_ios:
  #   type: build
  #   params:
  #     platform: ios
